  - name: Clean previous output
      run: rm -rf output

  - name: Export folder 1 (docs + sheets)
      uses: jonjonsson-chas/google-docs-to-markdown@main
        with:
          google_drive_folder_id: '1KY4aMu7o_gCZmq2YCNY0l3zeWrjhpowj'

      - name: Push folder 1 to repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          destination_dir: google_docs/folder1
          disable_nojekyll: true
          github_token: ${{ github.token }}
          publish_branch: main
          publish_dir: output
