name: Sync Google Docs to GitHub
on:
  workflow_dispatch:

permissions:
  contents: 'write'
  id-token: 'write'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          service_account: 'my-service-account@teamjonity.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/213617463337/locations/global/workloadIdentityPools/github/providers/my-repo'

      - name: Sync folder 1
        uses: r7kamura/google-docs-to-github@v3.0.1
        with:
          google_drive_folder_id: '1KY4aMu7o_gCZmq2YCNY0l3zeWrjhpowj'
          github_directory: 'google_docs/folder1'

      - name: Sync folder 2
        uses: r7kamura/google-docs-to-github@v3.0.1
        with:
          google_drive_folder_id: '1sinaL0YtKhye-QX4brsBHrJKZMu3ic5r'
          github_directory: 'google_docs/folder2'

      - name: Sync folder 3
        uses: r7kamura/google-docs-to-github@v3.0.1
        with:
          google_drive_folder_id: '1IxFOMTUMFKmPawL6ec7GmDPOt5N_ihfP'
          github_directory: 'google_docs/folder3'
